#include "include/Containerfile.header"

FROM --platform=linux/${BUILDARCH} \
    ${BUILD_CONTAINER_IMAGE}:${CONTAINER_VERSION} \
    as build-uboot

ARG UBOOT_VERSION

RUN \
	dnf5 install -y \
		awk \
		bc \
		bison \
		bzip2 \
		dtc \
		flex \
		gcc \
		git \
		gnutls-devel \
		libuuid-devel \
		make \
		ncurses-devel \
		openssl-devel \
		openssl-devel-engine \
		perl-interpreter \
		python3-devel \
		python3-libfdt \
		python3-pyelftools \
		python3-setuptools \
		swig \
		tar \
		wget \
	&& \
	git clone https://gitlab.collabora.com/hardware-enablement/rockchip-3588/rkbin.git \
	&& \
	git clone https://gitlab.collabora.com/hardware-enablement/rockchip-3588/trusted-firmware-a -b rk3588 \
	&& \
	pushd trusted-firmware-a \
	&& \
	make \
		CC=gcc \
		HOSTCC=gcc \
		PLAT=rk3588 \
		bl31 \
	&& \
	popd \
	&& \
	wget https://ftp.denx.de/pub/u-boot/u-boot-${UBOOT_VERSION}.tar.bz2 \
	&& \
	tar xf ./u-boot-${UBOOT_VERSION}.tar.bz2 \
	&& \
	pushd u-boot-${UBOOT_VERSION} \
	&& \
	make rock5b-rk3588_defconfig \
	&& \
	ROCKCHIP_TPL=../rkbin/bin/rk35/rk3588_ddr_lp4_2112MHz_lp5_2400MHz_v1.18.bin \
	   BL31=../trusted-firmware-a/build/rk3588/release/bl31/bl31.elf \
	       make \
				-j $(nproc) \
	&& \
	popd \
	&& \
    cp u-boot-${UBOOT_VERSION}/idbloader.img ./ \
    && \
    cp u-boot-${UBOOT_VERSION}/u-boot.itb ./

FROM --platform=linux/arm64 \
    ${CONTAINER_IMAGE}:${CONTAINER_VERSION}

COPY overlays/common/gpt/ /
COPY overlays/aarch64/rockchip/rk3588/ /

#include "include/Containerfile.target.gpt"

COPY --from=build-uboot /idbloader.img /
COPY --from=build-uboot /u-boot.itb /

CMD ["/bin/sh"]
