#include "include/Containerfile.header"

#include "include/Containerfile.build.mbr"

FROM --platform=linux/arm64 \
    ${BUILD_CONTAINER_IMAGE}:40 \
    as build-uboot

RUN \
	dnf5 install -y \
		dnf5-plugins \
	&& \
	dnf5 copr -y enable @centos-automotive-sig/ti-board-support \
	&& \
	dnf5 install -y \
		ti-uboot-images-armv8

FROM --platform=linux/arm64 \
    ${CONTAINER_IMAGE}:${CONTAINER_VERSION}

COPY overlays/common/mbr/ /
COPY overlays/aarch64/ti/am625/ /

#include "include/Containerfile.target.mbr"

COPY --from=build-uboot /usr/share/uboot/am62x_evm_r5/tiboot3-am62x-gp-evm.bin /boot/efi/tiboot3.bin
COPY --from=build-uboot /usr/share/uboot/am62x_evm_a53/tispl.bin /boot/efi/tispl.bin
COPY --from=build-uboot /usr/share/uboot/am62x_evm_a53/u-boot.img /boot/efi/u-boot.img

CMD ["/bin/sh"]
