#include "include/Containerfile.header"

ARG BUILD_MBR_PART_ESP_FS_VOL_ID="cbe82c91"
ARG BUILD_MBR_PART_BOOT_FS_UUID="51694d0d-69ba-4fbe-b3fb-cb03d4fa0eab"
ARG BUILD_MBR_PART_ROOT_FS_UUID="a69a423d-ad2e-4925-8d77-c4e27980fdb4"

ARG BUILD_DIR_R5=/build/r5/
ARG BUILD_DIR_A53=/build/a53/

#include "include/Containerfile.build.mbr"

FROM --platform=linux/arm64 \
    ${BUILD_CONTAINER_IMAGE}:40 \
    as build-uboot

ARG AARCH32_CROSS_COMPILE=arm-linux-gnu-
ARG AARCH64_CROSS_COMPILE=aarch64-linux-gnu-
ARG TI_FIRMWARE_VERSION=11.00.09

ARG ATF_VERSION
ARG OPTEE_VERSION
ARG UBOOT_VERSION
ARG BUILD_DIR_A53
ARG BUILD_DIR_R5

RUN \
	dnf5 install -y \
		bc \
		bison \
		bzip2 \
		dtc \
		flex \
		gcc \
		gcc-aarch64-linux-gnu \
		gcc-arm-linux-gnu \
		gnutls-devel \
		libuuid-devel \
		make \
		ncurses-devel \
		openssl \
		openssl-devel \
		openssl-devel-engine \
		perl-interpreter \
		python3-cryptography \
		python3-devel \
		python3-jsonschema \
		python3-libfdt \
		python3-pyelftools \
		python3-pyyaml \
		python3-setuptools \
		swig \
		tar \
		wget \
		yamllint \
	&& \
	wget https://git.ti.com/cgit/processor-firmware/ti-linux-firmware/snapshot/ti-linux-firmware-${TI_FIRMWARE_VERSION}.tar.gz \
	&& \
	tar xvf ./ti-linux-firmware-${TI_FIRMWARE_VERSION}.tar.gz \
	&& \
	wget \
		https://github.com/ARM-software/arm-trusted-firmware/archive/refs/tags/v${ATF_VERSION}.tar.gz \
		-O atf-${ATF_VERSION}.tar.gz \
	&& \
	tar xvf ./atf-${ATF_VERSION}.tar.gz \
	&& \
	make \
		CROSS_COMPILE=${AARCH64_CROSS_COMPILE} \
		ARCH=aarch64 \
		PLAT=k3 \
		SPD=opteed \
		TARGET_BOARD=lite \
		-C ./arm-trusted-firmware-${ATF_VERSION} \
		-j $(nproc) \
	&& \
	wget \
		https://github.com/OP-TEE/optee_os/archive/refs/tags/${OPTEE_VERSION}.tar.gz \
		-O optee-${OPTEE_VERSION}.tar.gz \
	&& \
	tar xvf ./optee-${OPTEE_VERSION}.tar.gz \
	&& \
	make \
		CROSS_COMPILE=${AARCH32_CROSS_COMPILE} \
		CROSS_COMPILE64=${AARCH64_CROSS_COMPILE} \
		CFG_ARM64_core=y \
		CFG_WITH_SOFTWARE_PRNG=y \
		PLATFORM=k3-am62x \
		-C ./optee_os-${OPTEE_VERSION} \
		-j $(nproc) \
	&& \
	wget https://ftp.denx.de/pub/u-boot/u-boot-${UBOOT_VERSION}.tar.bz2 \
	&& \
	tar xvf ./u-boot-${UBOOT_VERSION}.tar.bz2 \
	&& \
	make \
		ARCH=arm \
		CROSS_COMPILE=${AARCH32_CROSS_COMPILE} \
		-C u-boot-${UBOOT_VERSION} \
		O=${BUILD_DIR_R5} \
		am62x_evm_r5_defconfig \
	&& \
	ls -l $(pwd)/ti-linux-firmware-${TI_FIRMWARE_VERSION} \
	&& \
	make \
		ARCH=arm \
		CROSS_COMPILE=${AARCH32_CROSS_COMPILE} \
		BINMAN_INDIRS=$(pwd)/ti-linux-firmware-${TI_FIRMWARE_VERSION} \
		-C u-boot-${UBOOT_VERSION} \
		O=${BUILD_DIR_R5} \
		-j $(nproc) \
	&& \
	make \
		ARCH=arm \
		CROSS_COMPILE=${AARCH64_CROSS_COMPILE} \
		-C u-boot-${UBOOT_VERSION} \
		O=${BUILD_DIR_A53} \
		am62x_evm_a53_defconfig \
	&& \
	make \
		ARCH=arm \
		CROSS_COMPILE=${AARCH64_CROSS_COMPILE} \
		BINMAN_INDIRS=$(pwd)/ti-linux-firmware-${TI_FIRMWARE_VERSION} \
		BL31=$(pwd)/arm-trusted-firmware-${ATF_VERSION}/build/k3/lite/release/bl31.bin \
		TEE=$(pwd)/optee_os-${OPTEE_VERSION}/out/arm-plat-k3/core/tee-raw.bin \
		-C u-boot-${UBOOT_VERSION} \
		O=${BUILD_DIR_A53} \
		-j $(nproc)

FROM --platform=linux/arm64 \
    ${CONTAINER_IMAGE}:${CONTAINER_VERSION}

ARG BUILD_MBR_PART_ESP_FS_VOL_ID
ARG BUILD_MBR_PART_BOOT_FS_UUID
ARG BUILD_MBR_PART_ROOT_FS_UUID

ARG BUILD_DIR_A53
ARG BUILD_DIR_R5

LABEL com.github.mripard.ocibootstrap.table.partitions="[ \"esp\", \"boot\", \"root\" ]"
LABEL com.github.mripard.ocibootstrap.table.type="mbr"
LABEL com.github.mripard.ocibootstrap.partition.esp.flags.bootable="true"
LABEL com.github.mripard.ocibootstrap.partition.esp.fs="fat"
LABEL com.github.mripard.ocibootstrap.partition.esp.fat.heads="64"
LABEL com.github.mripard.ocibootstrap.partition.esp.fat.sectors_per_track="32"
LABEL com.github.mripard.ocibootstrap.partition.esp.fat.vol_id="$BUILD_MBR_PART_ESP_FS_VOL_ID"
LABEL com.github.mripard.ocibootstrap.partition.esp.mount_point="/boot/efi"
LABEL com.github.mripard.ocibootstrap.partition.esp.size_mb="256"
LABEL com.github.mripard.ocibootstrap.partition.esp.type="0x0c"
LABEL com.github.mripard.ocibootstrap.partition.boot.fs="ext4"
LABEL com.github.mripard.ocibootstrap.partition.boot.ext4.uuid="$BUILD_MBR_PART_BOOT_FS_UUID"
LABEL com.github.mripard.ocibootstrap.partition.boot.mount_point="/boot"
LABEL com.github.mripard.ocibootstrap.partition.boot.size_mb="256"
LABEL com.github.mripard.ocibootstrap.partition.boot.type="0x83"
LABEL com.github.mripard.ocibootstrap.partition.root.fs="ext4"
LABEL com.github.mripard.ocibootstrap.partition.root.ext4.uuid="$BUILD_MBR_PART_ROOT_FS_UUID"
LABEL com.github.mripard.ocibootstrap.partition.root.mount_point="/"
LABEL com.github.mripard.ocibootstrap.partition.root.type="0x83"

COPY overlays/common/mbr/ /
COPY overlays/aarch64/ti/am625/ /

#include "include/Containerfile.target.mbr"

COPY --from=build-uboot ${BUILD_DIR_R5}/tiboot3-am62x-gp-evm.bin /boot/efi/tiboot3.bin
COPY --from=build-uboot ${BUILD_DIR_A53}/tispl.bin /boot/efi/tispl.bin
COPY --from=build-uboot ${BUILD_DIR_A53}/u-boot.img /boot/efi/u-boot.img

CMD ["/bin/sh"]
