#include "include/Containerfile.header"

FROM --platform=linux/${BUILDARCH} \
    ${BUILD_CONTAINER_IMAGE}:${CONTAINER_VERSION} \
    as build-uboot

RUN \
	dnf5 install -y \
		uboot-images-armv8

FROM --platform=linux/arm64 \
    ${CONTAINER_IMAGE}:${CONTAINER_VERSION}

COPY overlays/common/gpt/ /
COPY overlays/aarch64/rockchip/rk3399/ /

#include "include/Containerfile.target.gpt"

COPY --from=build-uboot /usr/share/uboot/pinephone-pro-rk3399/u-boot-rockchip.bin /

CMD ["/bin/sh"]
