#include "include/Containerfile.header"

#include "include/Containerfile.build.mbr"

FROM --platform=linux/${BUILDARCH} \
    ${BUILD_CONTAINER_IMAGE}:${CONTAINER_VERSION} \
    as build-uboot

ARG UBOOT_VERSION

RUN \
	dnf5 install -y \
		awk \
		bc \
		bison \
		bzip2 \
		dtc \
		flex \
		gcc \
		git \
		gnutls-devel \
		libuuid-devel \
		make \
		ncurses-devel \
		openssl-devel \
		openssl-devel-engine \
		perl-interpreter \
		python3-devel \
		python3-libfdt \
		python3-pyelftools \
		python3-setuptools \
		qemu \
		swig \
		tar \
		wget \
	&& \
	wget https://ftp.denx.de/pub/u-boot/u-boot-${UBOOT_VERSION}.tar.bz2 \
	&& \
	tar xf ./u-boot-${UBOOT_VERSION}.tar.bz2 \
	&& \
	pushd u-boot-${UBOOT_VERSION} \
	&& \
	make khadas-vim3_defconfig \
	&& \
	make -j $(nproc) \
	&& \
	popd \
	&& \
	git clone https://github.com/LibreELEC/amlogic-boot-fip --depth=1 \
	&& \
	pushd amlogic-boot-fip \
	&& \
	mkdir out \
	&& \
	./build-fip.sh khadas-vim3 ../u-boot-${UBOOT_VERSION}/u-boot.bin out

FROM --platform=linux/arm64 \
    ${CONTAINER_IMAGE}:${CONTAINER_VERSION}

COPY overlays/common/mbr/ /
COPY overlays/aarch64/amlogic/a311d/ /

#include "include/Containerfile.target.mbr"

COPY --from=build-uboot /amlogic-boot-fip/out/u-boot.bin /u-boot.bin

CMD ["/bin/sh"]
