RUN \
    echo "uninitialized" > /etc/machine-id \
    && \
    passwd -d root \
    && \
	dnf5 install -y \
		e2fsprogs \
		kernel \
		kernel-core \
		kernel-modules \
		systemd-networkd \
		systemd-resolved \
		vim-minimal \
	&& \
    rm -f \
        /etc/machine-info \
        /var/lib/systemd/random-seed \
        /var/lib/systemd/credential.secret
