#include "include/Containerfile.header"

FROM --platform=linux/arm64 \
    ${CONTAINER_IMAGE}:${CONTAINER_VERSION}

COPY overlays/common/gpt/ /
COPY overlays/aarch64/arm/systemready-ir /

#include "include/Containerfile.target.gpt"

CMD ["/bin/sh"]
