#include "include/Containerfile.header"

FROM --platform=linux/${BUILDARCH} \
    ${BUILD_CONTAINER_IMAGE}:${CONTAINER_VERSION} \
    as build-uboot

ARG ATF_IMX_VERSION=lf-6.6.36-2.1.0
ARG FIRMWARE_IMX_VERSION=8.25
ARG FIRMWARE_IMX_REVISION=27879f8
ARG UBOOT_VERSION

ENV CROSS_COMPILE=aarch64-linux-gnu-

RUN \
	dnf5 install -y \
		awk \
		bc \
		bison \
		bzip2 \
		dtc \
		flex \
		gcc \
		gcc-aarch64-linux-gnu \
		gnutls-devel \
		libuuid-devel \
		make \
		ncurses-devel \
		openssl-devel \
		openssl-devel-engine \
		perl-interpreter \
		python3-devel \
		python3-libfdt \
		python3-setuptools \
		swig \
		tar \
		wget \
	&& \
	wget https://github.com/nxp-imx/imx-atf/archive/${ATF_IMX_VERSION}/imx-atf-${ATF_IMX_VERSION}.tar.gz \
	&& \
	tar xvf ./imx-atf-${ATF_IMX_VERSION}.tar.gz \
	&& \
	pushd ./imx-atf-${ATF_IMX_VERSION} \
	&& \
	make \
		PLAT=imx8mp \
		bl31 \
	&& \
	popd \
	&& \
	wget https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/firmware-imx-${FIRMWARE_IMX_VERSION}-${FIRMWARE_IMX_REVISION}.bin \
	&& \
	chmod +x ./firmware-imx-${FIRMWARE_IMX_VERSION}-${FIRMWARE_IMX_REVISION}.bin \
	&& \
	./firmware-imx-${FIRMWARE_IMX_VERSION}-${FIRMWARE_IMX_REVISION}.bin \
		--force \
		--auto-accept \
	&& \
	wget https://ftp.denx.de/pub/u-boot/u-boot-${UBOOT_VERSION}.tar.bz2 \
	&& \
	tar xvf ./u-boot-${UBOOT_VERSION}.tar.bz2 \
	&& \
	pushd u-boot-${UBOOT_VERSION} \
	&& \
	make O=/build imx8mp_debix_model_a_defconfig \
	&& \
	cp \
		../imx-atf-${ATF_IMX_VERSION}/build/imx8mp/release/bl31.bin \
		../firmware-imx-${FIRMWARE_IMX_VERSION}-${FIRMWARE_IMX_REVISION}/firmware/ddr/synopsys/lpddr4_pmu_train_1d_dmem_202006.bin \
		../firmware-imx-${FIRMWARE_IMX_VERSION}-${FIRMWARE_IMX_REVISION}/firmware/ddr/synopsys/lpddr4_pmu_train_1d_imem_202006.bin \
		../firmware-imx-${FIRMWARE_IMX_VERSION}-${FIRMWARE_IMX_REVISION}/firmware/ddr/synopsys/lpddr4_pmu_train_2d_dmem_202006.bin \
		../firmware-imx-${FIRMWARE_IMX_VERSION}-${FIRMWARE_IMX_REVISION}/firmware/ddr/synopsys/lpddr4_pmu_train_2d_imem_202006.bin \
		/build \
	&& \
	make \
		NO_LTO=1 \
		O=/build \
		-j $(nproc)

FROM --platform=linux/arm64 \
    ${CONTAINER_IMAGE}:${CONTAINER_VERSION}

COPY overlays/common/gpt/ /
COPY overlays/aarch64/nxp/imx8mp/ /

#include "include/Containerfile.target.gpt"

COPY --from=build-uboot /build/flash.bin /flash.bin

CMD ["/bin/sh"]
