#include "include/Containerfile.header"

FROM --platform=linux/${BUILDARCH} \
    ${BUILD_CONTAINER_IMAGE}:${CONTAINER_VERSION} \
    as build-uboot

ARG ATF_IMX_VERSION=lf-6.6.36-2.1.0
ARG FIRMWARE_IMX_VERSION=8.25
ARG FIRMWARE_IMX_REVISION=27879f8
ARG UBOOT_VERSION=2024.10

ENV CROSS_COMPILE=aarch64-linux-gnu-

RUN \
	dnf5 install -y \
		bc \
		bison \
		bzip2 \
		dtc \
		flex \
		gcc \
		gcc-aarch64-linux-gnu \
		gnutls-devel \
		libuuid-devel \
		make \
		ncurses-devel \
		openssl-devel \
		openssl-devel-engine \
		perl-interpreter \
		python3-devel \
		python3-libfdt \
		python3-setuptools \
		swig \
		tar \
		wget \
	&& \
	wget https://github.com/nxp-imx/imx-atf/archive/${ATF_IMX_VERSION}/imx-atf-${ATF_IMX_VERSION}.tar.gz \
	&& \
	tar xvf ./imx-atf-${ATF_IMX_VERSION}.tar.gz \
	&& \
	pushd ./imx-atf-${ATF_IMX_VERSION} \
	&& \
	make \
		PLAT=imx8mp \
		bl31 \
	&& \
	popd \
	&& \
	wget https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/firmware-imx-${FIRMWARE_IMX_VERSION}-${FIRMWARE_IMX_REVISION}.bin \
	&& \
	chmod +x ./firmware-imx-${FIRMWARE_IMX_VERSION}-${FIRMWARE_IMX_REVISION}.bin \
	&& \
	./firmware-imx-${FIRMWARE_IMX_VERSION}-${FIRMWARE_IMX_REVISION}.bin \
		--force \
		--auto-accept \
	&& \
	wget https://ftp.denx.de/pub/u-boot/u-boot-${UBOOT_VERSION}.tar.bz2 \
	&& \
	tar xvf ./u-boot-${UBOOT_VERSION}.tar.bz2 \
	&& \
	pushd u-boot-${UBOOT_VERSION} \
	&& \
	make O=/build imx8mp_debix_model_a_defconfig \
	&& \
	cp \
		../imx-atf-${ATF_IMX_VERSION}/build/imx8mp/release/bl31.bin \
		../firmware-imx-${FIRMWARE_IMX_VERSION}-${FIRMWARE_IMX_REVISION}/firmware/ddr/synopsys/lpddr4_pmu_train_1d_dmem_202006.bin \
		../firmware-imx-${FIRMWARE_IMX_VERSION}-${FIRMWARE_IMX_REVISION}/firmware/ddr/synopsys/lpddr4_pmu_train_1d_imem_202006.bin \
		../firmware-imx-${FIRMWARE_IMX_VERSION}-${FIRMWARE_IMX_REVISION}/firmware/ddr/synopsys/lpddr4_pmu_train_2d_dmem_202006.bin \
		../firmware-imx-${FIRMWARE_IMX_VERSION}-${FIRMWARE_IMX_REVISION}/firmware/ddr/synopsys/lpddr4_pmu_train_2d_imem_202006.bin \
		/build \
	&& \
	make \
		NO_LTO=1 \
		O=/build \
		-j $(nproc)

FROM --platform=linux/arm64 \
    ${CONTAINER_IMAGE}:${CONTAINER_VERSION}

LABEL com.github.mripard.ocibootstrap.table.partitions="[ \"loader\", \"esp\", \"root\" ]"
LABEL com.github.mripard.ocibootstrap.table.type="gpt"
LABEL com.github.mripard.ocibootstrap.partition.loader.fs="raw"
LABEL com.github.mripard.ocibootstrap.partition.loader.raw.content="/flash.bin"
LABEL com.github.mripard.ocibootstrap.partition.loader.size_mb="2"
LABEL com.github.mripard.ocibootstrap.partition.loader.offset_lba="64"
LABEL com.github.mripard.ocibootstrap.partition.loader.flags.required="true"
LABEL com.github.mripard.ocibootstrap.partition.loader.partition_uuid="8da63339-0007-60c0-c436-083ac8230908"
LABEL com.github.mripard.ocibootstrap.partition.esp.flags.bootable="true"
LABEL com.github.mripard.ocibootstrap.partition.esp.flags.required="true"
LABEL com.github.mripard.ocibootstrap.partition.esp.fs="fat"
LABEL com.github.mripard.ocibootstrap.partition.esp.mount_point="/efi"
LABEL com.github.mripard.ocibootstrap.partition.esp.partition_uuid="c12a7328-f81f-11d2-ba4b-00a0c93ec93b"
LABEL com.github.mripard.ocibootstrap.partition.esp.size_mb="512"
LABEL com.github.mripard.ocibootstrap.partition.root.fs="ext4"
LABEL com.github.mripard.ocibootstrap.partition.root.mount_point="/"
LABEL com.github.mripard.ocibootstrap.partition.root.partition_uuid="b921b045-1df0-41c3-af44-4c6f280d3fae"

COPY overlays/common/gpt/ /
COPY overlays/aarch64/nxp/imx8mp/ /

RUN \
	mkdir -p /efi/EFI/BOOT/ \
	&& \
	dnf5 install -y \
		sdubby \
		systemd-boot-unsigned \
	&& \
	cp /usr/lib/systemd/boot/efi/systemd-bootaa64.efi /efi/EFI/BOOT/BOOTAA64.efi

#include "include/Containerfile.target.common"

RUN [ "/bin/bash", "-c", "sed -i 's|/efi/|/|' /efi/loader/entries/*.conf" ]

COPY --from=build-uboot /build/flash.bin /flash.bin

CMD ["/bin/sh"]
